# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    cmds:
      - task: proto
      - task: build-all

  proto:
    desc: Compile protobuf schemas for Go
    cmds:
      - mkdir -p client/ipc
      - >
        protoc 
        --go_out=client/ipc --go_opt=paths=source_relative 
        --go-grpc_out=client/ipc --go-grpc_opt=paths=source_relative 
        -I proto proto/decentis.proto
    sources:
      - proto/*.proto
    generates:
      - client/ipc/*.go

  build-daemon:
    desc: Build Rust daemon binary
    cmds:
      - cd daemon && cargo build

  build-client:
    desc: Build Go client binary
    cmds:
      - cd client && go build -o ../bin/decentis .

  build-all:
    desc: Build both daemon and client
    cmds:
      - task: build-daemon
      - task: build-client
