// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: decentis.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonControl_GetStatus_FullMethodName    = "/decentis.v1.DaemonControl/GetStatus"
	DaemonControl_InitiateSend_FullMethodName = "/decentis.v1.DaemonControl/InitiateSend"
)

// DaemonControlClient is the client API for DaemonControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonControlClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	InitiateSend(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error)
}

type daemonControlClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonControlClient(cc grpc.ClientConnInterface) DaemonControlClient {
	return &daemonControlClient{cc}
}

func (c *daemonControlClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonControlClient) InitiateSend(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonControl_ServiceDesc.Streams[0], DaemonControl_InitiateSend_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendFileRequest, TransferProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonControl_InitiateSendClient = grpc.ServerStreamingClient[TransferProgress]

// DaemonControlServer is the server API for DaemonControl service.
// All implementations must embed UnimplementedDaemonControlServer
// for forward compatibility.
type DaemonControlServer interface {
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	InitiateSend(*SendFileRequest, grpc.ServerStreamingServer[TransferProgress]) error
	mustEmbedUnimplementedDaemonControlServer()
}

// UnimplementedDaemonControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonControlServer struct{}

func (UnimplementedDaemonControlServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonControlServer) InitiateSend(*SendFileRequest, grpc.ServerStreamingServer[TransferProgress]) error {
	return status.Error(codes.Unimplemented, "method InitiateSend not implemented")
}
func (UnimplementedDaemonControlServer) mustEmbedUnimplementedDaemonControlServer() {}
func (UnimplementedDaemonControlServer) testEmbeddedByValue()                       {}

// UnsafeDaemonControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonControlServer will
// result in compilation errors.
type UnsafeDaemonControlServer interface {
	mustEmbedUnimplementedDaemonControlServer()
}

func RegisterDaemonControlServer(s grpc.ServiceRegistrar, srv DaemonControlServer) {
	// If the following call panics, it indicates UnimplementedDaemonControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonControl_ServiceDesc, srv)
}

func _DaemonControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonControlServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonControl_InitiateSend_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonControlServer).InitiateSend(m, &grpc.GenericServerStream[SendFileRequest, TransferProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonControl_InitiateSendServer = grpc.ServerStreamingServer[TransferProgress]

// DaemonControl_ServiceDesc is the grpc.ServiceDesc for DaemonControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decentis.v1.DaemonControl",
	HandlerType: (*DaemonControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DaemonControl_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitiateSend",
			Handler:       _DaemonControl_InitiateSend_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "decentis.proto",
}
