// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: decentis.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_decentis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decentis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_decentis_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirtualIp     string                 `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ActivePeers   int32                  `protobuf:"varint,3,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_decentis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decentis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_decentis_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *StatusResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StatusResponse) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	PeerVirtualIp string                 `protobuf:"bytes,2,opt,name=peer_virtual_ip,json=peerVirtualIp,proto3" json:"peer_virtual_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_decentis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decentis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_decentis_proto_rawDescGZIP(), []int{2}
}

func (x *SendFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SendFileRequest) GetPeerVirtualIp() string {
	if x != nil {
		return x.PeerVirtualIp
	}
	return ""
}

type TransferProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	BytesTransferred uint64                 `protobuf:"varint,2,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	SpeedMbps        float64                `protobuf:"fixed64,4,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferProgress) Reset() {
	*x = TransferProgress{}
	mi := &file_decentis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgress) ProtoMessage() {}

func (x *TransferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_decentis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgress.ProtoReflect.Descriptor instead.
func (*TransferProgress) Descriptor() ([]byte, []int) {
	return file_decentis_proto_rawDescGZIP(), []int{3}
}

func (x *TransferProgress) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProgress) GetBytesTransferred() uint64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *TransferProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferProgress) GetSpeedMbps() float64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *TransferProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_decentis_proto protoreflect.FileDescriptor

const file_decentis_proto_rawDesc = "" +
	"\n" +
	"\x0edecentis.proto\x12\vdecentis.v1\"\x0f\n" +
	"\rStatusRequest\"o\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12!\n" +
	"\factive_peers\x18\x03 \x01(\x05R\vactivePeers\"V\n" +
	"\x0fSendFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12&\n" +
	"\x0fpeer_virtual_ip\x18\x02 \x01(\tR\rpeerVirtualIp\"\xb8\x01\n" +
	"\x10TransferProgress\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12+\n" +
	"\x11bytes_transferred\x18\x02 \x01(\x04R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x04 \x01(\x01R\tspeedMbps\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xa4\x01\n" +
	"\rDaemonControl\x12D\n" +
	"\tGetStatus\x12\x1a.decentis.v1.StatusRequest\x1a\x1b.decentis.v1.StatusResponse\x12M\n" +
	"\fInitiateSend\x12\x1c.decentis.v1.SendFileRequest\x1a\x1d.decentis.v1.TransferProgress0\x01B\x0eZ\fdecentis/ipcb\x06proto3"

var (
	file_decentis_proto_rawDescOnce sync.Once
	file_decentis_proto_rawDescData []byte
)

func file_decentis_proto_rawDescGZIP() []byte {
	file_decentis_proto_rawDescOnce.Do(func() {
		file_decentis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decentis_proto_rawDesc), len(file_decentis_proto_rawDesc)))
	})
	return file_decentis_proto_rawDescData
}

var file_decentis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_decentis_proto_goTypes = []any{
	(*StatusRequest)(nil),    // 0: decentis.v1.StatusRequest
	(*StatusResponse)(nil),   // 1: decentis.v1.StatusResponse
	(*SendFileRequest)(nil),  // 2: decentis.v1.SendFileRequest
	(*TransferProgress)(nil), // 3: decentis.v1.TransferProgress
}
var file_decentis_proto_depIdxs = []int32{
	0, // 0: decentis.v1.DaemonControl.GetStatus:input_type -> decentis.v1.StatusRequest
	2, // 1: decentis.v1.DaemonControl.InitiateSend:input_type -> decentis.v1.SendFileRequest
	1, // 2: decentis.v1.DaemonControl.GetStatus:output_type -> decentis.v1.StatusResponse
	3, // 3: decentis.v1.DaemonControl.InitiateSend:output_type -> decentis.v1.TransferProgress
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_decentis_proto_init() }
func file_decentis_proto_init() {
	if File_decentis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decentis_proto_rawDesc), len(file_decentis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decentis_proto_goTypes,
		DependencyIndexes: file_decentis_proto_depIdxs,
		MessageInfos:      file_decentis_proto_msgTypes,
	}.Build()
	File_decentis_proto = out.File
	file_decentis_proto_goTypes = nil
	file_decentis_proto_depIdxs = nil
}
