// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: signaling.proto

package signaling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalingService_StartConnection_FullMethodName = "/decentis.signaling.v1.SignalingService/StartConnection"
	SignalingService_SendSignal_FullMethodName      = "/decentis.signaling.v1.SignalingService/SendSignal"
)

// SignalingServiceClient is the client API for SignalingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalingServiceClient interface {
	// Registers the node and opens a server-push stream for peer events
	StartConnection(ctx context.Context, in *SignalMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalMessage], error)
	// Unary call to initiate actions (e.g., dial a peer, disconnect)
	SendSignal(ctx context.Context, in *SignalMessage, opts ...grpc.CallOption) (*SignalResponse, error)
}

type signalingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalingServiceClient(cc grpc.ClientConnInterface) SignalingServiceClient {
	return &signalingServiceClient{cc}
}

func (c *signalingServiceClient) StartConnection(ctx context.Context, in *SignalMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignalMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalingService_ServiceDesc.Streams[0], SignalingService_StartConnection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalMessage, SignalMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalingService_StartConnectionClient = grpc.ServerStreamingClient[SignalMessage]

func (c *signalingServiceClient) SendSignal(ctx context.Context, in *SignalMessage, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, SignalingService_SendSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalingServiceServer is the server API for SignalingService service.
// All implementations must embed UnimplementedSignalingServiceServer
// for forward compatibility.
type SignalingServiceServer interface {
	// Registers the node and opens a server-push stream for peer events
	StartConnection(*SignalMessage, grpc.ServerStreamingServer[SignalMessage]) error
	// Unary call to initiate actions (e.g., dial a peer, disconnect)
	SendSignal(context.Context, *SignalMessage) (*SignalResponse, error)
	mustEmbedUnimplementedSignalingServiceServer()
}

// UnimplementedSignalingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalingServiceServer struct{}

func (UnimplementedSignalingServiceServer) StartConnection(*SignalMessage, grpc.ServerStreamingServer[SignalMessage]) error {
	return status.Error(codes.Unimplemented, "method StartConnection not implemented")
}
func (UnimplementedSignalingServiceServer) SendSignal(context.Context, *SignalMessage) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSignal not implemented")
}
func (UnimplementedSignalingServiceServer) mustEmbedUnimplementedSignalingServiceServer() {}
func (UnimplementedSignalingServiceServer) testEmbeddedByValue()                          {}

// UnsafeSignalingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalingServiceServer will
// result in compilation errors.
type UnsafeSignalingServiceServer interface {
	mustEmbedUnimplementedSignalingServiceServer()
}

func RegisterSignalingServiceServer(s grpc.ServiceRegistrar, srv SignalingServiceServer) {
	// If the following call panics, it indicates UnimplementedSignalingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalingService_ServiceDesc, srv)
}

func _SignalingService_StartConnection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SignalMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignalingServiceServer).StartConnection(m, &grpc.GenericServerStream[SignalMessage, SignalMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalingService_StartConnectionServer = grpc.ServerStreamingServer[SignalMessage]

func _SignalingService_SendSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).SendSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignalingService_SendSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).SendSignal(ctx, req.(*SignalMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// SignalingService_ServiceDesc is the grpc.ServiceDesc for SignalingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "decentis.signaling.v1.SignalingService",
	HandlerType: (*SignalingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSignal",
			Handler:    _SignalingService_SendSignal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartConnection",
			Handler:       _SignalingService_StartConnection_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "signaling.proto",
}
