// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *SignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignalMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Using `oneof` allows us to multiplex different events over the same RPC methods
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*SignalMessage_Register
	//	*SignalMessage_Dial
	//	*SignalMessage_PeerFound
	//	*SignalMessage_Disconnect
	Payload       isSignalMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *SignalMessage) GetPayload() isSignalMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalMessage) GetRegister() *RegisterNode {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *SignalMessage) GetDial() *DialPeer {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Dial); ok {
			return x.Dial
		}
	}
	return nil
}

func (x *SignalMessage) GetPeerFound() *PeerFound {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_PeerFound); ok {
			return x.PeerFound
		}
	}
	return nil
}

func (x *SignalMessage) GetDisconnect() *DisconnectNode {
	if x != nil {
		if x, ok := x.Payload.(*SignalMessage_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isSignalMessage_Payload interface {
	isSignalMessage_Payload()
}

type SignalMessage_Register struct {
	Register *RegisterNode `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type SignalMessage_Dial struct {
	Dial *DialPeer `protobuf:"bytes,2,opt,name=dial,proto3,oneof"`
}

type SignalMessage_PeerFound struct {
	PeerFound *PeerFound `protobuf:"bytes,3,opt,name=peer_found,json=peerFound,proto3,oneof"`
}

type SignalMessage_Disconnect struct {
	Disconnect *DisconnectNode `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"` // 1. Added the disconnect payload variant
}

func (*SignalMessage_Register) isSignalMessage_Payload() {}

func (*SignalMessage_Dial) isSignalMessage_Payload() {}

func (*SignalMessage_PeerFound) isSignalMessage_Payload() {}

func (*SignalMessage_Disconnect) isSignalMessage_Payload() {}

type RegisterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Base64 Public Key of the node
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PublicPort    uint32                 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	LocalIp       string                 `protobuf:"bytes,4,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNode) Reset() {
	*x = RegisterNode{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNode) ProtoMessage() {}

func (x *RegisterNode) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNode.ProtoReflect.Descriptor instead.
func (*RegisterNode) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNode) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RegisterNode) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *RegisterNode) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

type DialPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MyNodeId      string                 `protobuf:"bytes,1,opt,name=my_node_id,json=myNodeId,proto3" json:"my_node_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialPeer) Reset() {
	*x = DialPeer{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialPeer) ProtoMessage() {}

func (x *DialPeer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialPeer.ProtoReflect.Descriptor instead.
func (*DialPeer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *DialPeer) GetMyNodeId() string {
	if x != nil {
		return x.MyNodeId
	}
	return ""
}

func (x *DialPeer) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type PeerFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PublicPort    uint32                 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	LocalIp       string                 `protobuf:"bytes,4,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerFound) Reset() {
	*x = PeerFound{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerFound) ProtoMessage() {}

func (x *PeerFound) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerFound.ProtoReflect.Descriptor instead.
func (*PeerFound) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *PeerFound) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *PeerFound) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *PeerFound) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *PeerFound) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

type DisconnectNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Base64 Public Key of the disconnecting node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectNode) Reset() {
	*x = DisconnectNode{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectNode) ProtoMessage() {}

func (x *DisconnectNode) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectNode.ProtoReflect.Descriptor instead.
func (*DisconnectNode) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\x15decentis.signaling.v1\"D\n" +
	"\x0eSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x02\n" +
	"\rSignalMessage\x12A\n" +
	"\bregister\x18\x01 \x01(\v2#.decentis.signaling.v1.RegisterNodeH\x00R\bregister\x125\n" +
	"\x04dial\x18\x02 \x01(\v2\x1f.decentis.signaling.v1.DialPeerH\x00R\x04dial\x12A\n" +
	"\n" +
	"peer_found\x18\x03 \x01(\v2 .decentis.signaling.v1.PeerFoundH\x00R\tpeerFound\x12G\n" +
	"\n" +
	"disconnect\x18\x04 \x01(\v2%.decentis.signaling.v1.DisconnectNodeH\x00R\n" +
	"disconnectB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\fRegisterNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\rR\n" +
	"publicPort\x12\x19\n" +
	"\blocal_ip\x18\x04 \x01(\tR\alocalIp\"N\n" +
	"\bDialPeer\x12\x1c\n" +
	"\n" +
	"my_node_id\x18\x01 \x01(\tR\bmyNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"\x8a\x01\n" +
	"\tPeerFound\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\rR\n" +
	"publicPort\x12\x19\n" +
	"\blocal_ip\x18\x04 \x01(\tR\alocalIp\")\n" +
	"\x0eDisconnectNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2\xce\x01\n" +
	"\x10SignalingService\x12_\n" +
	"\x0fStartConnection\x12$.decentis.signaling.v1.SignalMessage\x1a$.decentis.signaling.v1.SignalMessage0\x01\x12Y\n" +
	"\n" +
	"SendSignal\x12$.decentis.signaling.v1.SignalMessage\x1a%.decentis.signaling.v1.SignalResponseB%Z#decentis/server/signaling;signalingb\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_signaling_proto_goTypes = []any{
	(*SignalResponse)(nil), // 0: decentis.signaling.v1.SignalResponse
	(*SignalMessage)(nil),  // 1: decentis.signaling.v1.SignalMessage
	(*RegisterNode)(nil),   // 2: decentis.signaling.v1.RegisterNode
	(*DialPeer)(nil),       // 3: decentis.signaling.v1.DialPeer
	(*PeerFound)(nil),      // 4: decentis.signaling.v1.PeerFound
	(*DisconnectNode)(nil), // 5: decentis.signaling.v1.DisconnectNode
}
var file_signaling_proto_depIdxs = []int32{
	2, // 0: decentis.signaling.v1.SignalMessage.register:type_name -> decentis.signaling.v1.RegisterNode
	3, // 1: decentis.signaling.v1.SignalMessage.dial:type_name -> decentis.signaling.v1.DialPeer
	4, // 2: decentis.signaling.v1.SignalMessage.peer_found:type_name -> decentis.signaling.v1.PeerFound
	5, // 3: decentis.signaling.v1.SignalMessage.disconnect:type_name -> decentis.signaling.v1.DisconnectNode
	1, // 4: decentis.signaling.v1.SignalingService.StartConnection:input_type -> decentis.signaling.v1.SignalMessage
	1, // 5: decentis.signaling.v1.SignalingService.SendSignal:input_type -> decentis.signaling.v1.SignalMessage
	1, // 6: decentis.signaling.v1.SignalingService.StartConnection:output_type -> decentis.signaling.v1.SignalMessage
	0, // 7: decentis.signaling.v1.SignalingService.SendSignal:output_type -> decentis.signaling.v1.SignalResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	file_signaling_proto_msgTypes[1].OneofWrappers = []any{
		(*SignalMessage_Register)(nil),
		(*SignalMessage_Dial)(nil),
		(*SignalMessage_PeerFound)(nil),
		(*SignalMessage_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
